
# Site settings
title: Fragmentos filosóficos 
author: Cristina Noemí 
name: Noemi
email: imeonh4ze@gmail.com
description: "Un lugar para dar espacio a importantes fragmentos filosóficos" 

# Build settings 
remote_theme: jekyll/minima

theme: jekyll-theme-merlot